# Generated by Django 3.2 on 2021-04-09 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='libelle',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
