# Generated by Django 3.2 on 2021-04-10 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0004_unite'),
    ]

    operations = [
        migrations.AddField(
            model_name='personne',
            name='unite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myblog.unite'),
        ),
    ]
