# Generated by Django 3.2 on 2021-04-10 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0005_personne_unite'),
    ]

    operations = [
        migrations.AddField(
            model_name='personne',
            name='qte',
            field=models.IntegerField(null=True),
        ),
    ]
