# Generated by Django 3.2 on 2021-04-10 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0006_personne_qte'),
    ]

    operations = [
        migrations.AddField(
            model_name='personne',
            name='annee',
            field=models.IntegerField(null=True),
        ),
    ]
