# Generated by Django 3.2 on 2021-04-15 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0007_personne_annee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='libelle',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='produit',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
