# Generated by Django 3.2 on 2021-04-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0008_auto_20210415_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='dateprod',
            field=models.DateField(null=True),
        ),
    ]
