# Generated by Django 3.2 on 2021-04-20 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0009_produit_dateprod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='dateprod',
            field=models.DateTimeField(null=True),
        ),
    ]
