# Generated by Django 3.2 on 2021-04-22 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0015_article_facture'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='facture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myblog.facture'),
        ),
    ]
