# Generated by Django 3.2 on 2021-04-22 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0017_remove_article_facture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mouvement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte_cde', models.IntegerField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myblog.article')),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myblog.facture')),
            ],
            options={
                'db_table': 'mouvements',
            },
        ),
    ]
