# Generated by Django 3.2 on 2021-04-22 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0019_book_ecrivain'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Ecrivain',
        ),
    ]
