# Generated by Django 3.2 on 2021-04-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0023_auto_20210423_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='date_fact',
            field=models.DateField(null=True),
        ),
    ]
