# Generated by Django 3.2 on 2021-04-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0024_facture_date_fact'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudient',
            name='photo',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AlterUniqueTogether(
            name='operation',
            unique_together={('facture', 'article')},
        ),
    ]
