# Generated by Django 3.2 on 2021-04-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0027_remove_etudient_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudient',
            name='photo',
            field=models.FileField(null=True, upload_to='photos/'),
        ),
    ]
